# Generated by Django 4.2.7 on 2023-12-08 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0005_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ecommerceapp.userprofile'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='profile_images/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='shipping_address',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_address', models.TextField()),
                ('payment_method', models.CharField(max_length=50)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerceapp.cart')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ecommerceapp.order')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerceapp.userprofile')),
            ],
        ),
    ]
